#define COMMAND_ECHO "ECHO "
#define COMMAND_TIME "TIME"
#define COMMAND_CLOSE "CLOSE"
#define COMMAND_UPLOAD "UPLOAD "
#define COMMAND_DOWNLOAD "DOWNLOAD "

#define COMMAND_DOWNLOAD_LENGTH 8
#define COMMAND_ECHO_LENGTH 5
#define COMMAND_TIME_LENGTH 4
#define COMMAND_CLOSE_LENGTH 5

#define BUF_SIZE 256
#define COMMAND_MAX_LENGTH 16
#define COMMAND_COUNT 4

#define COMMAND_END_1 "34"
#define COMMAND_END_2 "34"